# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_linux
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_linux)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/linux/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=Linux -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Linux/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -Wl,-soname=libnode9.so
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_macosx)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.dylib
  OBJDIR = build/obj/macosx/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=MacOSX -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/MacOSX/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -framework Carbon -framework CoreFoundation -framework IOKit -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -m64 -dynamiclib -Wl,-install_name,@rpath/libnode9.dylib -undefined dynamic_lookup
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	rebase lib/libnode9.dylib
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_freebsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/freebsd/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=FreeBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/FreeBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_netbsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/netbsd/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=NetBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/NetBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_openbsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/openbsd/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=OpenBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/OpenBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_dragonfly)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/dragonfly/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=DragonFly -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Dragonfly/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_solaris)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/solaris/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_windows)
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/node9.dll
  OBJDIR = build/obj/windows/debug/libnode9
  DEFINES += /D"_UNICODE" /D"UNICODE" /D"SYSHOST=Linux" /D"OBJTYPE="386"" /D"SYSTARG=Nt" /D"EMU"
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Nt/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) /MDd /Z7
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) /MDd /Z7 /EHsc
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += 9.lib bio.lib sec.lib
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) /LIBPATH:"../luajit/src" /LIBPATH:"../libuv/.libs" /LIBPATH:"build" /NOLOGO /DLL /DEBUG
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:
endif

ifeq ($(config),debug_android)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/android/debug/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_linux)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/linux/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=Linux -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Linux/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -Wl,-soname=libnode9.so -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_macosx)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.dylib
  OBJDIR = build/obj/macosx/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=MacOSX -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/MacOSX/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -framework Carbon -framework CoreFoundation -framework IOKit -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -m64 -dynamiclib -Wl,-install_name,@rpath/libnode9.dylib -undefined dynamic_lookup
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	rebase lib/libnode9.dylib
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_freebsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/freebsd/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=FreeBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/FreeBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_netbsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/netbsd/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=NetBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/NetBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_openbsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/openbsd/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=OpenBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/OpenBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_dragonfly)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/dragonfly/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=DragonFly -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Dragonfly/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_solaris)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/solaris/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_windows)
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/node9.dll
  OBJDIR = build/obj/windows/devel/libnode9
  DEFINES += /D"_UNICODE" /D"UNICODE" /D"SYSHOST=Linux" /D"OBJTYPE="386"" /D"SYSTARG=Nt" /D"EMU"
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Nt/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) /MD
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) /MD /EHsc
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += 9.lib bio.lib sec.lib
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) /LIBPATH:"../luajit/src" /LIBPATH:"../libuv/.libs" /LIBPATH:"build" /NOLOGO /DLL
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:
endif

ifeq ($(config),devel_android)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/android/devel/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_linux)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/linux/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=Linux -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Linux/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -Wl,-soname=libnode9.so -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_macosx)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.dylib
  OBJDIR = build/obj/macosx/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=MacOSX -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/MacOSX/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -framework Carbon -framework CoreFoundation -framework IOKit -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -m64 -dynamiclib -Wl,-install_name,@rpath/libnode9.dylib -undefined dynamic_lookup
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	rebase lib/libnode9.dylib
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_freebsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/freebsd/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=FreeBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/FreeBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_netbsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/netbsd/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=NetBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/NetBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_openbsd)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/openbsd/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=OpenBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/OpenBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_dragonfly)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/dragonfly/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=DragonFly -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Dragonfly/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_solaris)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/solaris/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_windows)
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/node9.dll
  OBJDIR = build/obj/windows/release/libnode9
  DEFINES += /D"_UNICODE" /D"UNICODE" /D"SYSHOST=Linux" /D"OBJTYPE="386"" /D"SYSTARG=Nt" /D"EMU"
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Nt/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) /MD
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) /MD /EHsc
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += 9.lib bio.lib sec.lib
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) /LIBPATH:"../luajit/src" /LIBPATH:"../libuv/.libs" /LIBPATH:"build" /NOLOGO /DLL
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:
endif

ifeq ($(config),release_android)
  RESCOMP = windres
  TARGETDIR = ../lib
  TARGET = $(TARGETDIR)/libnode9.so
  OBJDIR = build/obj/android/release/libnode9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -shared -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/error.o \
	$(OBJDIR)/node9.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking libnode9
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning libnode9
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/error.o: styx/svcs/error.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/node9.o: styx/svcs/node9.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif