# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_linux
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_linux)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/linux/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=Linux -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Linux/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -ldl -lm -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -Wl,--export-dynamic
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_macosx)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/macosx/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=MacOSX -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/MacOSX/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -framework Carbon -framework CoreFoundation -framework IOKit -l9 -lbio -lsec -lluajit_s -luv_s -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -m64 -pagezero_size 10000 -image_base 100000000
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
	@echo Running prelink commands
	cd libuv/.libs; ln -sf libuv.a libuv_s.a; cd ../..; cd luajit/src; ln -sf libluajit.a libluajit_s.a; cd ../..
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_freebsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/freebsd/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=FreeBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/FreeBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lm -lkvm -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -Wl,--export-dynamic
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_netbsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/netbsd/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=NetBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/NetBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_openbsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/openbsd/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=OpenBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/OpenBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_dragonfly)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/dragonfly/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=DragonFly -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Dragonfly/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_solaris)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/solaris/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_windows)
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9.exe
  OBJDIR = build/obj/windows/debug/node9
  DEFINES += /D"_UNICODE" /D"UNICODE" /D"SYSHOST=Linux" /D"OBJTYPE="386"" /D"SYSTARG=Nt" /D"EMU"
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Nt/include -Iinclude -Istyx/svcs -Istyx/platform/Nt
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) /MDd /Z7
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) /MDd /Z7 /EHsc
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += 9.lib bio.lib sec.lib luajit.lib uv.lib m.lib netapi32.lib wsock32.lib user32.lib gdi32.lib advapi32.lib winmm.lib mpr.lib
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) /LIBPATH:"../luajit/src" /LIBPATH:"../libuv/.libs" /LIBPATH:"build" /NOLOGO /DEBUG
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:
endif

ifeq ($(config),debug_android)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/android/debug/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_linux)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/linux/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=Linux -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Linux/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -ldl -lm -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s -Wl,--export-dynamic
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_macosx)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/macosx/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=MacOSX -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/MacOSX/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -framework Carbon -framework CoreFoundation -framework IOKit -l9 -lbio -lsec -lluajit_s -luv_s -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -m64 -pagezero_size 10000 -image_base 100000000
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
	@echo Running prelink commands
	cd libuv/.libs; ln -sf libuv.a libuv_s.a; cd ../..; cd luajit/src; ln -sf libluajit.a libluajit_s.a; cd ../..
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_freebsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/freebsd/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=FreeBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/FreeBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lm -lkvm -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s -Wl,--export-dynamic
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_netbsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/netbsd/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=NetBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/NetBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_openbsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/openbsd/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=OpenBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/OpenBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_dragonfly)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/dragonfly/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=DragonFly -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Dragonfly/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_solaris)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/solaris/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),devel_windows)
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9.exe
  OBJDIR = build/obj/windows/devel/node9
  DEFINES += /D"_UNICODE" /D"UNICODE" /D"SYSHOST=Linux" /D"OBJTYPE="386"" /D"SYSTARG=Nt" /D"EMU"
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Nt/include -Iinclude -Istyx/svcs -Istyx/platform/Nt
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) /MD
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) /MD /EHsc
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += 9.lib bio.lib sec.lib luajit.lib uv.lib m.lib netapi32.lib wsock32.lib user32.lib gdi32.lib advapi32.lib winmm.lib mpr.lib
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) /LIBPATH:"../luajit/src" /LIBPATH:"../libuv/.libs" /LIBPATH:"build" /NOLOGO
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:
endif

ifeq ($(config),devel_android)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/android/devel/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_linux)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/linux/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=Linux -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Linux/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -ldl -lm -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s -Wl,--export-dynamic
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_macosx)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/macosx/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=MacOSX -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/MacOSX/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -framework Carbon -framework CoreFoundation -framework IOKit -l9 -lbio -lsec -lluajit_s -luv_s -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -m64 -pagezero_size 10000 -image_base 100000000
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
	@echo Running prelink commands
	cd libuv/.libs; ln -sf libuv.a libuv_s.a; cd ../..; cd luajit/src; ln -sf libluajit.a libluajit_s.a; cd ../..
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_freebsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/freebsd/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=FreeBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/FreeBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lm -lkvm -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s -Wl,--export-dynamic
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_netbsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/netbsd/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=NetBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/NetBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_openbsd)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/openbsd/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=OpenBSD -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/OpenBSD/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_dragonfly)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/dragonfly/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DSYSTARG=DragonFly -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Dragonfly/include -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_solaris)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/solaris/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_windows)
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9.exe
  OBJDIR = build/obj/windows/release/node9
  DEFINES += /D"_UNICODE" /D"UNICODE" /D"SYSHOST=Linux" /D"OBJTYPE="386"" /D"SYSTARG=Nt" /D"EMU"
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Istyx/platform/Nt/include -Iinclude -Istyx/svcs -Istyx/platform/Nt
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) /MD
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) /MD /EHsc
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += 9.lib bio.lib sec.lib luajit.lib uv.lib m.lib netapi32.lib wsock32.lib user32.lib gdi32.lib advapi32.lib winmm.lib mpr.lib
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) /LIBPATH:"../luajit/src" /LIBPATH:"../libuv/.libs" /LIBPATH:"build" /NOLOGO
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:
endif

ifeq ($(config),release_android)
  RESCOMP = windres
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/node9
  OBJDIR = build/obj/android/release/node9
  DEFINES += -DSYSHOST=Linux -DOBJTYPE=\"386\" -DEMU
  INCLUDES += -I../libuv/src -I../libuv/include -I../luajit/src -Istyx/hosting/libuv/include -Istyx/include -I../fs/module -Iinclude -Istyx/svcs
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -l9 -lbio -lsec -lluajit -luv -lpthread
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../luajit/src -L../libuv/.libs -Lbuild -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
	@echo Running prebuild commands
	styx/utils/ndate >include/kerndate.h
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/main.o \
	$(OBJDIR)/misc9.o \
	$(OBJDIR)/emu.o \
	$(OBJDIR)/os-uv.o \
	$(OBJDIR)/alloc.o \
	$(OBJDIR)/cache.o \
	$(OBJDIR)/chan.o \
	$(OBJDIR)/dev.o \
	$(OBJDIR)/devcap.o \
	$(OBJDIR)/devcmd.o \
	$(OBJDIR)/devcons.o \
	$(OBJDIR)/devdup.o \
	$(OBJDIR)/devenv.o \
	$(OBJDIR)/devindir.o \
	$(OBJDIR)/devip.o \
	$(OBJDIR)/devmem.o \
	$(OBJDIR)/devmnt.o \
	$(OBJDIR)/devpipe.o \
	$(OBJDIR)/devroot.o \
	$(OBJDIR)/devssl.o \
	$(OBJDIR)/devtab.o \
	$(OBJDIR)/dial.o \
	$(OBJDIR)/env.o \
	$(OBJDIR)/error.o \
	$(OBJDIR)/errstr.o \
	$(OBJDIR)/exportfs.o \
	$(OBJDIR)/exptab.o \
	$(OBJDIR)/ipaux.o \
	$(OBJDIR)/ipif-posix.o \
	$(OBJDIR)/kproc-libuv.o \
	$(OBJDIR)/latin1.o \
	$(OBJDIR)/lock.o \
	$(OBJDIR)/node9.o \
	$(OBJDIR)/parse.o \
	$(OBJDIR)/pgrp.o \
	$(OBJDIR)/print.o \
	$(OBJDIR)/proc.o \
	$(OBJDIR)/qio.o \
	$(OBJDIR)/random.o \
	$(OBJDIR)/styx.o \
	$(OBJDIR)/sysfile.o \
	$(OBJDIR)/uqid.o \
	$(OBJDIR)/vm.o \

RESOURCES := \

CUSTOMFILES := \

ifeq ($(config),debug_linux)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-Linux-X86_64.o \
	$(OBJDIR)/cmd1.o \
	$(OBJDIR)/devfs1.o \
	$(OBJDIR)/os1.o \
	$(OBJDIR)/segflush-386.o \

endif

ifeq ($(config),debug_macosx)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-MacOSX-X86_64.o \
	$(OBJDIR)/cmd2.o \
	$(OBJDIR)/devfs2.o \
	$(OBJDIR)/os2.o \

endif

ifeq ($(config),debug_freebsd)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-FreeBSD-X86_64.o \
	$(OBJDIR)/cmd.o \
	$(OBJDIR)/devfs.o \
	$(OBJDIR)/os.o \

endif

ifeq ($(config),debug_windows)
  OBJECTS += \
	$(OBJDIR)/cmd3.o \
	$(OBJDIR)/devfs3.o \
	$(OBJDIR)/os3.o \
	$(OBJDIR)/r16.o \

endif

ifeq ($(config),devel_linux)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-Linux-X86_64.o \
	$(OBJDIR)/cmd1.o \
	$(OBJDIR)/devfs1.o \
	$(OBJDIR)/os1.o \
	$(OBJDIR)/segflush-386.o \

endif

ifeq ($(config),devel_macosx)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-MacOSX-X86_64.o \
	$(OBJDIR)/cmd2.o \
	$(OBJDIR)/devfs2.o \
	$(OBJDIR)/os2.o \

endif

ifeq ($(config),devel_freebsd)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-FreeBSD-X86_64.o \
	$(OBJDIR)/cmd.o \
	$(OBJDIR)/devfs.o \
	$(OBJDIR)/os.o \

endif

ifeq ($(config),devel_windows)
  OBJECTS += \
	$(OBJDIR)/cmd3.o \
	$(OBJDIR)/devfs3.o \
	$(OBJDIR)/os3.o \
	$(OBJDIR)/r16.o \

endif

ifeq ($(config),release_linux)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-Linux-X86_64.o \
	$(OBJDIR)/cmd1.o \
	$(OBJDIR)/devfs1.o \
	$(OBJDIR)/os1.o \
	$(OBJDIR)/segflush-386.o \

endif

ifeq ($(config),release_macosx)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-MacOSX-X86_64.o \
	$(OBJDIR)/cmd2.o \
	$(OBJDIR)/devfs2.o \
	$(OBJDIR)/os2.o \

endif

ifeq ($(config),release_freebsd)
  OBJECTS += \
	$(OBJDIR)/getcallerpc-FreeBSD-X86_64.o \
	$(OBJDIR)/cmd.o \
	$(OBJDIR)/devfs.o \
	$(OBJDIR)/os.o \

endif

ifeq ($(config),release_windows)
  OBJECTS += \
	$(OBJDIR)/cmd3.o \
	$(OBJDIR)/devfs3.o \
	$(OBJDIR)/os3.o \
	$(OBJDIR)/r16.o \

endif

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking node9
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning node9
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/main.o: main.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/misc9.o: misc9.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/emu.o: styx/hosting/libuv/emu.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/os-uv.o: styx/hosting/libuv/os-uv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/getcallerpc-FreeBSD-X86_64.o: styx/libs/lib9/getcallerpc-FreeBSD-X86_64.s
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/getcallerpc-Linux-X86_64.o: styx/libs/lib9/getcallerpc-Linux-X86_64.s
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/getcallerpc-MacOSX-X86_64.o: styx/libs/lib9/getcallerpc-MacOSX-X86_64.s
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cmd.o: styx/platform/FreeBSD/cmd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devfs.o: styx/platform/FreeBSD/devfs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/os.o: styx/platform/FreeBSD/os.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cmd1.o: styx/platform/Linux/cmd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devfs1.o: styx/platform/Linux/devfs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/os1.o: styx/platform/Linux/os.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/segflush-386.o: styx/platform/Linux/segflush-386.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cmd2.o: styx/platform/MacOSX/cmd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devfs2.o: styx/platform/MacOSX/devfs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/os2.o: styx/platform/MacOSX/os.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cmd3.o: styx/platform/Nt/cmd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devfs3.o: styx/platform/Nt/devfs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/os3.o: styx/platform/Nt/os.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r16.o: styx/platform/Nt/r16.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/alloc.o: styx/svcs/alloc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cache.o: styx/svcs/cache.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chan.o: styx/svcs/chan.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dev.o: styx/svcs/dev.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devcap.o: styx/svcs/devcap.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devcmd.o: styx/svcs/devcmd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devcons.o: styx/svcs/devcons.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devdup.o: styx/svcs/devdup.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devenv.o: styx/svcs/devenv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devindir.o: styx/svcs/devindir.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devip.o: styx/svcs/devip.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devmem.o: styx/svcs/devmem.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devmnt.o: styx/svcs/devmnt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devpipe.o: styx/svcs/devpipe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devroot.o: styx/svcs/devroot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devssl.o: styx/svcs/devssl.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/devtab.o: styx/svcs/devtab.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dial.o: styx/svcs/dial.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/env.o: styx/svcs/env.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/error.o: styx/svcs/error.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/errstr.o: styx/svcs/errstr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exportfs.o: styx/svcs/exportfs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exptab.o: styx/svcs/exptab.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ipaux.o: styx/svcs/ipaux.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ipif-posix.o: styx/svcs/ipif-posix.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/kproc-libuv.o: styx/svcs/kproc-libuv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/latin1.o: styx/svcs/latin1.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lock.o: styx/svcs/lock.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/node9.o: styx/svcs/node9.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/parse.o: styx/svcs/parse.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pgrp.o: styx/svcs/pgrp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/print.o: styx/svcs/print.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/proc.o: styx/svcs/proc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/qio.o: styx/svcs/qio.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/random.o: styx/svcs/random.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/styx.o: styx/svcs/styx.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sysfile.o: styx/svcs/sysfile.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/uqid.o: styx/svcs/uqid.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vm.o: styx/svcs/vm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif